package com.java11to17;

import java.util.Objects;

public class Records {


    //The equals, hashCode, and toString methods, as well as the private, final fields and public constructor,
    // are generated by the Java compiler.
    public record newWayPerson(String name, String address) {
    }


    public class OldWayPerson {

        private final String name;
        private final String address;

        public OldWayPerson(String name, String address) {
            this.name = name;
            this.address = address;
        }

        @Override
        public int hashCode() {
            return Objects.hash(name, address);
        }

        @Override
        public boolean equals(Object obj) {
            if (this == obj) {
                return true;
            } else if (!(obj instanceof OldWayPerson)) {
                return false;
            } else {
                OldWayPerson other = (OldWayPerson) obj;
                return Objects.equals(name, other.name)
                        && Objects.equals(address, other.address);
            }
        }

        @Override
        public String toString() {
            return "Person [name=" + name + ", address=" + address + "]";
        }

        // standard getters
    }
}
